[Service]
    Host = "edgex-watermill-producer"
    Port = 80
    Protocol = "http"
    StartupMsg = "watermill example producer"
    RequestTimeout = "30s"

[Writable]
    LogLevel = "TRACE"
    [Writable.StoreAndForward]
        Enabled = true
        RetryInterval = "30s"
        MaxRetries = 5

[Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
        path = "jetstream"
        [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Database]
    Type = "jetstream"
    Host = "broker"
    Port = 4222

[Trigger]
    Type = "http"

[ApplicationSettings]
    MessageBusType = "jetstream"
    BrokerUrl = "nats://broker:4222"
    MessageBusPublishTopic = "singlebasetopic"
    WireFormat = "raw"
    ClientID="test-producer"
    EncryptionAlgorithm="aes256-sha512"
    EncryptionKey="217A24432646294A404E635266556A586E3272357538782F413F442A472D4B6150645367566B59703373367639792442264529482B4D6251655468576D5A7134"